### Create a new user
POST http://localhost:8080/auth/sign-up
Content-Type: application/json

{
  "name": "Some name",
  "username": "Some username",
  "password": "password"
}


###
POST http://localhost:8080/auth/sign-in
Content-Type: application/json

{
  "username": "Some username",
  "password": "password"
}